services:
  frontend-dev:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: development
    container_name: beacon-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: pnpm dev --host 0.0.0.0
    environment:
      - NODE_ENV=development
    networks:
      - beacon-network

  frontend-storybook:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: development
    container_name: beacon-storybook
    ports:
      - "6006:6006"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: pnpm storybook --host 0.0.0.0
    environment:
      - NODE_ENV=development
    networks:
      - beacon-network

  frontend-test:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: development
    container_name: beacon-vitest
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: pnpm run test:unit
    environment:
      - NODE_ENV=test
    tty: true
    stdin_open: true
    networks:
      - beacon-network
      
  backend-dev:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: development
    container_name: beacon-backend-dev
    ports:
      - "5002:8080"
    volumes:
      - ../backend:/src/backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb
    networks:
      - beacon-network
      
  typegen:
    build:
      context: ..
      dockerfile: ./backend/DockerfileTypeGen
    container_name: beacon-typegen
    restart: "no"
    volumes:
      - ../frontend/src/shared/models/generated:/typegen/generated
      - ../backend:/app/backend
    networks:
      - beacon-network
          
  mongodb:
    image: mongo:7.0
    container_name: beacon-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=beacon
    volumes:
      - mongodb_data:/data/db
    networks:
      - beacon-network
        
  mailpit:
    image: axllent/mailpit
    container_name: beacon-mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - beacon-network

networks:
  beacon-network:
    driver: bridge
    
volumes:
  mongodb_data: