services:
  frontend-deploy:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: deploy
    container_name: beacon-frontend-deploy
    ports:
      - "8976:8976"
    env_file:
      - ../frontend/.env.deploy
    environment:
      - NODE_ENV=deploy
    networks:
      - beacon-network
    volumes:
      - ../frontend:/app
      - /app/node_modules
         
  backend-deploy:
    build:
      context: ../backend
      dockerfile: DockerfileDeploy
    container_name: beacon-backend-deploy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    env_file:
      - ../backend/.env.deploy
    networks:
      - beacon-network
      
  typegen:
    build:
      context: ..
      dockerfile: ./backend/DockerfileTypeGen
    container_name: beacon-typegen
    restart: "no"
    volumes:
      - ../frontend/src/shared/models/generated:/typegen/generated
      - ../backend:/app/backend
    networks:
      - beacon-network

networks:
  beacon-network:
    driver: bridge