services:
  frontend-deploy:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: deploy
    container_name: beacon-frontend-deploy
    ports:
      - "8976:8976"
    env_file:
      - ../frontend/.env.deploy
    environment:
      - NODE_ENV=deploy
    networks:
      - beacon-network
    volumes:
      - ../frontend:/app
      - /app/node_modules

networks:
  beacon-network:
    driver: bridge