# This is a generated file. Not intended for manual editing.
services:
  backend-dev:
    build:
      context: "/Users/kyleboehlen/RiderProjects/beacon/backend"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-musl-arm64/dotnet/dotnet"
    - "exec"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57597"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "backend:dev"
    ports:
    - "127.0.0.1:57197:57000"
    - "127.0.0.1:57397:57200"
    - "127.0.0.1:57597:57597"
    volumes:
    - "/Users/kyleboehlen/RiderProjects/beacon/backend:/app:rw"
    - "/Users/kyleboehlen/RiderProjects/beacon:/src:rw"
    - "/Users/kyleboehlen/.nuget/packages:/root/.nuget/packages"
    - "/Users/kyleboehlen/.local/share/JetBrains/RiderRemoteDebugger/2025.2.1/LinuxMuslArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/kyleboehlen/Library/Logs/JetBrains/Rider2025.2/DebuggerWorker/JetBrains.Debugger.Worker.2025_9_17_12_56_47:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  typegen:
    build:
      context: "/Users/kyleboehlen/RiderProjects/beacon"
      dockerfile: "./backend/DockerfileTypeGen"
      args:
        BUILD_CONFIGURATION: "Debug"
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57598"
    - "--timeout=60"
    environment:
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    ports:
    - "127.0.0.1:57198:57000"
    - "127.0.0.1:57398:57200"
    - "127.0.0.1:57598:57598"
    volumes:
    - "/Users/kyleboehlen/.local/share/JetBrains/RiderRemoteDebugger/2025.2.1/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/kyleboehlen/Library/Logs/JetBrains/Rider2025.2/DebuggerWorker/JetBrains.Debugger.Worker.2025_9_17_12_56_47:/var/opt/JetBrains/RiderDebuggerTools:rw"
